# Generated by Django 3.2.4 on 2021-06-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='nome',
            new_name='name',
        ),
    ]
